# Generated by Django 6.0.3 on 2026-03-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quizsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sizu_points',
            field=models.IntegerField(default=0, help_text='Puntos acumulados por el estudiante'),
        ),
        migrations.DeleteModel(
            name='QuizSession',
        ),
    ]
