# Generated by Django 6.0.3 on 2026-03-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_sizu_points_delete_quizsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sizu_points',
        ),
    ]
