# Generated by Django 6.0.3 on 2026-03-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_sizu_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sizu_points',
            field=models.IntegerField(default=0, help_text='Puntos acumulados por el estudiante'),
        ),
    ]
